const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const {createClient,makeTables}=require('./fixtures/kpi-fixture.cjs');
const box={exports:{},AbortController,Date,Intl,setTimeout,clearTimeout};vm.runInNewContext(ts.transpileModule(fs.readFileSync('kpi-workspace.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,box);const api=box.FlowMateKpi,user={id:'test-lead',role:'member',can_access_all_teams:true};
const m=(s,id)=>api.metrics(s).find(v=>v.id===id),base=(id,kind,extra={})=>({id:1,work_item_id:id,kind,actor_user_id:'test-owner',recorded_at:'2026-09-02T00:00:00+07:00',...extra});
test('organization calendar excludes the user-provided holidays, weekends and unknown years',()=>{
assert.equal(api.organizationCalendar.holidays.length,19);assert.equal(api.workingDays('2026-04-10T12:00:00+07:00','2026-04-16T12:00:00+07:00'),1);assert.equal(api.workingDays('2026-10-12T12:00:00+07:00','2026-10-14T12:00:00+07:00'),1);assert.equal(api.workingDays('2026-09-04T12:00:00+07:00','2026-09-07T12:00:00+07:00'),1);assert.equal(api.workingDays('2025-12-31T00:00:00+07:00','2026-01-03T00:00:00+07:00'),null);assert.equal(api.workingDays('2026-01-03T00:00:00+07:00','2026-01-02T00:00:00+07:00'),null);
});
test('Creative punctuality uses the original endpoint agreement and excludes uncovered work',async()=>{
const t=makeTables();t.creative_kpi_milestones.push({work_item_id:'creative-1',milestone:'review',occurred_at:'2026-09-03T00:00:00+07:00'});t.flowmate_kpi_measurement_evidence=[base('creative-1','deadline',{endpoint:'creative_draft',due_date:'2026-09-02'}),base('creative-1','deadline',{id:2,endpoint:'creative_draft',due_date:'2026-09-05',recorded_at:'2026-09-02T01:00:00+07:00'})];const s=await api.load(createClient(t),user,'creative','2026-09');assert.equal(m(s,'C01').value,0);assert.equal(m(s,'C01').eligible.length,1);assert.equal(api.metricRows(m(s,'C01'))[0].result,'ไม่เข้าเกณฑ์');assert.ok(api.csv(s,m(s,'C01')).includes('ไม่เข้าเกณฑ์'));assert.equal(m(s,'C02').value,null);
});
test('receiver confirmation enables turnaround; later acceptance does not rewrite completed work',async()=>{
const t=makeTables(),s=await api.load(createClient(t),user,'creative','2026-09');assert.ok(m(s,'C03').value>0);assert.ok(m(s,'C03').note.includes('เวลารวมเฉลี่ย'));t.creative_kpi_brief_evidence.forEach(b=>{if(b.action==='accepted')b.occurred_at='2026-09-30T00:00:00+07:00'});const late=await api.load(createClient(t),user,'creative','2026-09');assert.equal(m(late,'C03').value,null);
});
test('Requester urgency is frozen at intake and SLA needs confirmation plus a versioned agreement',async()=>{
const t=makeTables();t.flowmate_kpi_measurement_evidence=[base('creative-1','intake',{priority_at_intake:'urgent'}),base('creative-2','intake',{id:2,priority_at_intake:'normal'}),base('creative-1','sla',{id:3,recorded_at:'2026-09-01T00:00:00+07:00',required_on:'2026-09-09',sla_workdays:3,calendar_version:'organization-2026-v1'})];t.flowmate_creative_kpi_report_v.forEach(w=>w.priority='urgent');const s=await api.load(createClient(t),user,'requester','2026-09');assert.equal(m(s,'R02').value,50);assert.equal(m(s,'R02').eligible.length,2);assert.equal(m(s,'R01').value,100);assert.equal(m(s,'R01').eligible.length,1);assert.equal(m(s,'R03').value,14/18*100);
});
test('Task durations use start/submit and ready/approve separately, with distinct overdue stages',async()=>{
const t=makeTables();t.work_item_events.push({id:900,work_item_id:'task-1',created_at:'2026-09-02T05:00:00Z',to_status:'in_progress',metadata:{source:'task_assign_workspace',action:'start'}});t.flowmate_kpi_measurement_evidence=[base('task-1','ready',{brief_fingerprint:'confirmed-version'}),base('task-1','deadline',{id:2,endpoint:'task_submit',due_date:'2026-09-03'}),base('task-1','deadline',{id:3,endpoint:'task_approve',due_date:'2026-09-08'}),base('task-15','deadline',{id:4,endpoint:'task_submit',due_date:'2026-09-03'}),base('task-15','deadline',{id:5,endpoint:'task_approve',due_date:'2026-09-09'})];const s=await api.load(createClient(t),user,'task','2026-09');assert.equal(m(s,'T01').value,0);assert.equal(m(s,'T10').value,100);assert.equal(m(s,'T02').value,2);assert.ok(m(s,'T04').value>0);assert.equal(m(s,'T08S').cohort.length,0);assert.equal(m(s,'T08F').eligible.length,1);assert.equal(m(s,'T08F').value,100);
});
test('a missing measurement schema keeps R03 and existing counts available; source failures do not become zero',async()=>{
const t=makeTables(),s=await api.load(createClient(t,{response:(r,q)=>q.name==='flowmate_kpi_measurement_evidence'?{data:null,count:null,error:{code:'PGRST205'}}:r}),user,'requester','2026-09');assert.equal(s.resources.evidence.status,'unavailable');assert.equal(s.partial,false);assert.equal(m(s,'R02').value,null);assert.equal(m(s,'R03').value,14/18*100);assert.ok(api.csv(s,m(s,'R03')));
const failed=await api.load(createClient(t,{fail:q=>q.name==='flowmate_kpi_measurement_evidence'}),user,'requester','2026-09');assert.equal(failed.partial,true);assert.equal(m(failed,'R02').value,null);
});
test('a team forward invalidates previous receiving-team deadlines and ready confirmations',async()=>{
const t=makeTables();t.work_item_events.push({id:901,work_item_id:'task-1',created_at:'2026-09-03T00:00:00+07:00',metadata:{source:'task_assign_workspace',action:'forward'}});t.flowmate_kpi_measurement_evidence=[base('task-1','deadline',{endpoint:'task_approve',due_date:'2026-09-08'}),base('task-1','ready',{id:2,brief_fingerprint:'old-team'})];const s=await api.load(createClient(t),user,'task','2026-09');assert.equal(m(s,'T10').value,null);assert.equal(m(s,'T04').value,null);
});
test('CSAT loads the full reporting quarter rather than only tasks completed in the selected month',async()=>{
const t=makeTables();t.work_items.push({id:'old-task',display_id:'QT-OLD-DEMO',title:'Synthetic earlier-quarter task',work_type:'quick_task',status:'delivered',created_at:'2026-07-01T00:00:00Z',archived_at:null,requester_team:'Marketing'});t.flowmate_kpi_measurement_evidence=[base('old-task','csat',{id:999,work_domain:'quick_task',recorded_at:'2026-07-15T00:00:00Z',score:4,survey_definition:'internal-csat-1to5-v1',survey_period:'2026-Q3'})];const s=await api.load(createClient(t),user,'task','2026-09');assert.equal(m(s,'T12').value,4);assert.equal(m(s,'T12').unit,'score');assert.equal(m(s,'T12').cohort.length,1);assert.equal(m(s,'T12').event,'surveyAt');assert.equal(api.metrics(s,{team:'Operations'}).find(v=>v.id==='T12').value,null);
});
test('plan type is independent of urgent priority and brief edits invalidate ready evidence',async()=>{
const t=makeTables();t.flowmate_kpi_measurement_evidence=[base('task-1','intake',{plan_at_intake:'planned',priority_at_intake:'urgent'}),base('task-2','intake',{id:2,plan_at_intake:'unplanned',priority_at_intake:'normal'}),base('task-1','ready',{id:3,brief_fingerprint:'previous'})];t.work_item_events.push({id:991,work_item_id:'task-1',created_at:'2026-09-03T00:00:00Z',metadata:{source:'task_assign_workspace',action:'edit_brief'}});const s=await api.load(createClient(t),user,'task','2026-09');assert.equal(m(s,'T11').value,50);assert.equal(m(s,'T11').eligible.length,2);assert.equal(m(s,'T04').value,null);
});
test('late receiver confirmation is an SLA failure rather than missing evidence',async()=>{
const t=makeTables();t.flowmate_kpi_measurement_evidence=[base('creative-1','sla',{recorded_at:'2026-09-01T00:00:00+07:00',required_on:'2026-09-01',sla_workdays:3,calendar_version:'organization-2026-v1'})];const s=await api.load(createClient(t),user,'requester','2026-09');assert.equal(m(s,'R01').value,0);assert.equal(m(s,'R01').eligible.length,1);
});
test('Task ready evidence is displayed and exported, and failed endpoint sources suppress punctuality',async()=>{
const t=makeTables();t.flowmate_kpi_measurement_evidence=[base('task-1','ready',{brief_fingerprint:'current'}),base('task-1','deadline',{id:2,endpoint:'task_submit',due_date:'2026-09-05'})];const s=await api.load(createClient(t),user,'task','2026-09');assert.equal(api.facts(s).find(f=>f.id==='task-1').readyAt,'2026-09-02T00:00:00+07:00');assert.ok(api.csv(s,m(s,'T01')).includes('2026-09-02T00:00:00+07:00'));s.resources.taskCandidates.status='error';assert.equal(m(s,'T01').value,null);
});
test('CSV confirmation is bound to the measured event, not a later brief version',async()=>{
const t=makeTables();t.creative_kpi_brief_evidence.push({id:9990,work_item_id:'creative-1',action:'submitted',occurred_at:'2026-09-20T00:00:00+07:00',brief_link:'https://example.com/later'},{id:9991,work_item_id:'creative-1',action:'accepted',submission_id:9990,actor_user_id:'receiver',reason:'later version',occurred_at:'2026-09-21T00:00:00+07:00',brief_link:'https://example.com/later'});const s=await api.load(createClient(t),user,'creative','2026-09'),metric=m(s,'C03');assert.ok(metric.value>0);const line=api.csv(s,metric).split('\r\n').find(v=>v.includes('CR-DEMO-1"'));assert.ok(line.includes('2026-09-02T05:00:00Z'));assert.ok(!line.includes('2026-09-21T00:00:00+07:00'));
});
