import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {beforeAll,afterAll,it,expect} from 'vitest';
let db:PGlite;
const uid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const call=async(sql:string,args:unknown[]=[])=>{const r=await db.query<{v:any}>(sql,args);return r.rows[0]?.v;};
async function as(n:number|string|null){await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n===null?'':typeof n==='number'?uid(n):n]);}
beforeAll(async()=>{db=new PGlite();await db.exec(readFileSync('src/lib/activity-automation/monitor-fixture.sql','utf8'));
 // The current summary's CASE projection resolves this relation even in TEST/BP paths.
 // No production records or runner are installed in this isolated security fixture.
 await db.exec('create table activity_automation_private.production_observations(activity text,project_code text,period text,state text,code text,observed_at timestamptz,source_row integer)');
 const acceptance=readFileSync('supabase/activity_automation_acceptance_release.sql','utf8').match(/create or replace function activity_automation_private\.has_accepted_brief\(p_work uuid\)[\s\S]*?\$\$;/)?.[0];
 if(!acceptance)throw new Error('real acceptance helper missing');await db.exec(acceptance);
 await db.exec(readFileSync('supabase/activity_automation_monitor.sql','utf8'));},30000);
afterAll(async()=>db.close());
it('rejects anonymous and inactive users',async()=>{for(const n of [null,4]){await as(n);await expect(call('select activity_automation_monitor_access() v')).rejects.toThrow('access denied');}});
it('separates ops, BP-only, dual and regular user capabilities',async()=>{
 for(const [id,shared,bp] of [[1,true,false],[2,true,true],[3,false,false],['5abad25d-3e8c-4a0d-baa6-0a0615ba00fc',false,true]] as const){await as(id);const v=await call('select activity_automation_monitor_access() v');expect(v.data).toMatchObject({sharedRead:shared,battlePassRead:bp,sharedDiagnosis:false});}
});
it('revokes anon/public/private helper execution and adds only authenticated entrypoints',async()=>{
 expect(await call("select has_function_privilege('anon','public.activity_automation_monitor_access()','EXECUTE') v")).toBe(false);
 expect(await call("select has_function_privilege('authenticated','public.activity_automation_monitor_access()','EXECUTE') v")).toBe(true);
 expect(await call("select has_function_privilege('authenticated','activity_automation_private.monitor_access()','EXECUTE') v")).toBe(false);
 await as(1);await db.exec('set role authenticated');try{expect((await call('select activity_automation_monitor_access() v')).data.sharedRead).toBe(true);}finally{await db.exec('reset role');}
});
it('returns source-specific denied coverage without leaking BP rows',async()=>{await as(1);const v=await call("select activity_automation_monitor_runs('production','2026-09') v");expect(v.sources.find((s:any)=>s.source==='battle_pass').status).toBe('forbidden');expect(v.data.rows).toEqual([]);});
it('counts outputs once despite attempts and joins current acceptance separately from assignment',async()=>{await as(1);const v=await call("select activity_automation_monitor_summary('test','2026-09') v");expect(v.sources.find((s:any)=>s.source==='shared')).toMatchObject({status:'ok'});expect(v.data.cards).toMatchObject({supportedActivities:4,outputs:1,pendingBriefs:0,complete:true});expect(v.data.outputs[0]).toMatchObject({displayId:'CR-1265',briefState:'accepted',assignmentState:'assigned'});expect(JSON.stringify(v)).not.toContain('DO_NOT_EXPOSE');});
it('invalidates acceptance after resubmission and link mismatch',async()=>{
 await as(1);await db.exec("insert into creative_kpi_brief_evidence values(3,'10000000-0000-4000-8000-000000000001','submitted',null,'https://docs.google.com/presentation/d/fixture/edit')");
 let v=await call("select activity_automation_monitor_summary('test','2026-09') v");expect(v.data.cards.pendingBriefs).toBe(1);expect(v.data.outputs[0].assignmentState).toBe('assigned');
 await db.exec("insert into creative_kpi_brief_evidence values(4,'10000000-0000-4000-8000-000000000001','accepted',3,null)");
 v=await call("select activity_automation_monitor_summary('test','2026-09') v");expect(v.data.cards.pendingBriefs).toBe(0);
 await db.exec("update creative_request_details set brief_link='changed'");v=await call("select activity_automation_monitor_summary('test','2026-09') v");expect(v.data.cards.pendingBriefs).toBe(1);
 await db.exec("update creative_request_details set brief_link='https://docs.google.com/presentation/d/fixture/edit'");
});
it('paginates equal timestamps without duplicates, uses Bangkok bounds and rejects cursor scope changes',async()=>{
 await as(1);let cursor:null|string=null;const ids:string[]=[];do{const v=await call("select activity_automation_monitor_runs('test','2026-09',null,null,null,$1,1) v",[cursor]);ids.push(...v.data.rows.map((x:any)=>x.id));cursor=v.data.nextCursor;
 if(cursor)await expect(call("select activity_automation_monitor_runs('test','2026-10',null,null,null,$1,1) v",[cursor])).rejects.toThrow('Invalid monitor cursor');}while(cursor);
 expect(ids).toHaveLength(3);expect(new Set(ids).size).toBe(3);expect(ids[2]).toBe('30000000-0000-4000-8000-000000000003');
});
it('keeps campaign-month summary separate from event-month history and validates filters',async()=>{await as(1);expect((await call("select activity_automation_monitor_summary('test','2026-10') v")).data.cards.outputs).toBe(0);for(const [mode,month] of [['oops','2026-09'],['test','2026-13']])await expect(call('select activity_automation_monitor_summary($1,$2) v',[mode,month])).rejects.toThrow('Invalid monitor filter');await expect(call("select activity_automation_monitor_runs('test','2026-09',null,null,null,'broken',25) v")).rejects.toThrow('Invalid monitor cursor');});
it('rejects guessed cross-source and mismatched entity IDs',async()=>{await as(1);await expect(call("select activity_automation_monitor_run('battle_pass','60000000-0000-4000-8000-000000000001','tick') v")).rejects.toThrow('access denied');await expect(call("select activity_automation_monitor_run('shared','60000000-0000-4000-8000-000000000001','run') v")).rejects.toThrow('Run not found');await expect(call("select activity_automation_monitor_run('shared','30000000-0000-4000-8000-000000000001','tick') v")).rejects.toThrow('Run not found');expect((await call("select activity_automation_monitor_run('shared','30000000-0000-4000-8000-000000000001','run') v")).data.outputs).toHaveLength(1);});
it('normalizes delivery semantics without provider IDs or recipients',async()=>{await as(2);const bp=await call("select activity_automation_monitor_notifications('production','2026-09') v");expect(bp.data.rows[0]).toMatchObject({status:'delivered',rawStatus:'sent',providerAccepted:true});expect(JSON.stringify(bp)).not.toContain('secret_provider');const shared=await call("select activity_automation_monitor_notifications('test','2026-09') v");expect(shared.data.rows[0].status).toBe('uncertain');expect(JSON.stringify(shared)).not.toContain('DO_NOT_EXPOSE');});
it('retains good-source rows and marks total incomplete on another source failure',async()=>{await as(2);await db.exec('alter table activity_automation_private.runs rename to broken_runs');try{const v=await call("select activity_automation_monitor_runs('production','2026-09') v");expect(v.data.rows).toHaveLength(1);expect(v.sources.find((s:any)=>s.source==='shared').status).toBe('unavailable');const summary=await call("select activity_automation_monitor_summary('production','2026-09') v");expect(summary.data.cards.complete).toBe(false);}finally{await db.exec('alter table activity_automation_private.broken_runs rename to runs');}});
it('keeps constraints and data unchanged across read calls',async()=>{await as(1);const before=await call('select count(*) v from creative_kpi_brief_evidence');await call("select activity_automation_monitor_summary('test','2026-09') v");expect(await call('select count(*) v from creative_kpi_brief_evidence')).toBe(before);await expect(db.exec("update activity_automation_private.settings set production_enabled=true")).rejects.toThrow();});
it('does not count failed generation with a persisted binding as successful',async()=>{await as(1);await db.exec("update activity_automation_private.runs set state='failed' where id='30000000-0000-4000-8000-000000000001'");try{const v=await call("select activity_automation_monitor_summary('test','2026-09') v");expect(v.data.cards.outputs).toBe(0);expect(v.data.outputs[0].complete).toBe(false);}finally{await db.exec("update activity_automation_private.runs set state='ready_for_review' where id='30000000-0000-4000-8000-000000000001'");}});
it('uses campaign month for bound incidents and event month only for orphan incidents',async()=>{await as(1);await db.exec("insert into activity_automation_private.incidents values('40000000-0000-4000-8000-000000000002','30000000-0000-4000-8000-000000000002','membership','MEM-202610','source','source_invalid',1,'2026-09-18T00:00Z','2026-09-18T00:00Z')");
 const sep=await call("select activity_automation_monitor_summary('test','2026-09','membership') v");expect(sep.data.attention.map((x:any)=>x.projectCode)).toEqual(['ORPHAN']);
 const oct=await call("select activity_automation_monitor_summary('test','2026-10','membership') v");expect(oct.data.attention[0]).toMatchObject({projectCode:'MEM-202610',campaignUnbound:false});
});
it('regular members cannot read rows or guessed detail',async()=>{await as(3);const v=await call("select activity_automation_monitor_runs('test','2026-09') v");expect(v.data.rows).toEqual([]);expect(v.sources.every((x:any)=>x.status==='forbidden')).toBe(true);await expect(call("select activity_automation_monitor_run('shared','30000000-0000-4000-8000-000000000001') v")).rejects.toThrow('access denied');});
it('opens pre-output monthly TEST detail and keeps it distinct from production tick',async()=>{await as(2);await db.exec("insert into battle_pass_private.monthly_runs(mode,period,state,updated_at) values('test','2026-09','failed','2026-09-18T00:00Z')");const v=await call("select activity_automation_monitor_run('battle_pass','test:2026-09','monthly') v");expect(v.data.run).toMatchObject({entityType:'monthly',status:'failed'});expect(v.data.outputs).toEqual([]);await expect(call("select activity_automation_monitor_run('battle_pass','test:2026-09','tick') v")).rejects.toThrow('Run not found');});
it('keeps an unavailable activity visible and ignores outages outside selected activity scope',async()=>{await as(2);await db.exec('alter table activity_automation_private.runs rename to broken_runs');try{
 const all=await call("select activity_automation_monitor_summary('production','2026-09') v");expect(all.data.activities.filter((x:any)=>x.availability==='unavailable')).toHaveLength(4);
 const bp=await call("select activity_automation_monitor_summary('production','2026-09','battle_pass') v");expect(bp.data.cards.complete).toBe(true);expect(bp.data.activities).toHaveLength(1);
 const page=await call("select activity_automation_monitor_runs('production','2026-09','battle_pass') v");expect(page.sources.some((s:any)=>s.source==='shared')).toBe(false);
}finally{await db.exec('alter table activity_automation_private.broken_runs rename to runs');}});
it('malformed dates cannot break a source or create a fake campaign month',async()=>{await as(1);await db.exec("update activity_automation_private.runs set model=jsonb_set(model,'{source,startDate}','\"2026-02-31\"') where id='30000000-0000-4000-8000-000000000001'");try{const v=await call("select activity_automation_monitor_run('shared','30000000-0000-4000-8000-000000000001') v");expect(v.data.outputs[0].campaignStart).toBeNull();expect((await call("select activity_automation_monitor_summary('test','2026-02') v")).data.cards.outputs).toBe(0);}finally{await db.exec("update activity_automation_private.runs set model=jsonb_set(model,'{source,startDate}','\"2026-09-09\"') where id='30000000-0000-4000-8000-000000000001'");}});
it('shows BP current blocking evidence and stale health, not recovered older failures',async()=>{await as(2);await db.exec("insert into battle_pass_private.production_ticks values('60000000-0000-4000-8000-000000000002','2026-09-19T00:00Z','source_blocked','source_invalid','{\"period\":\"2026-09\"}'); update battle_pass_private.monthly_settings set enabled=true;update cron.job set active=true");
 await db.exec("update battle_pass_private.production_ticks set checked_at=current_timestamp-interval '2 hours'");
 let v=await call("select activity_automation_monitor_summary('production','2026-09') v");expect(v.data.attention.some((x:any)=>x.status==='source_blocked')).toBe(true);expect(v.data.attention.some((x:any)=>x.status==='stale')).toBe(true);
 await db.exec("insert into battle_pass_private.production_ticks values('60000000-0000-4000-8000-000000000003',current_timestamp-interval '1 hour','complete',null,'{\"period\":\"2026-09\"}')");v=await call("select activity_automation_monitor_summary('production','2026-09') v");expect(v.data.attention.some((x:any)=>x.status==='source_blocked')).toBe(false);await db.exec('update battle_pass_private.monthly_settings set enabled=false;update cron.job set active=false');
});
it('paginates over 25 mixed-source equal timestamps and caps limit at 100',async()=>{await as(2);await db.exec("insert into activity_automation_private.runs(id,activity,mode,is_test,project_code,state,stage,attempt_count,created_at,updated_at,model) select ('80000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'membership','test',true,'P-'||n,'discovered','source',0,'2026-09-18T00:00Z','2026-09-18T00:00Z','{}' from generate_series(1,105) n");
 const page=await call("select activity_automation_monitor_runs('test','2026-09') v");expect(page.data.rows).toHaveLength(25);expect(page.data.hasMore).toBe(true);
 const ids:string[]=[];let cursor:null|string=null;do{const v=await call("select activity_automation_monitor_runs('test','2026-09',null,null,null,$1,25) v",[cursor]);ids.push(...v.data.rows.map((x:any)=>x.source+':'+x.id));cursor=v.data.nextCursor;}while(cursor);expect(ids).toHaveLength(109);expect(new Set(ids).size).toBe(ids.length);expect(ids.some(id=>id.startsWith('battle_pass:'))).toBe(true);
 expect((await call("select activity_automation_monitor_runs('test','2026-09',null,null,null,null,9999) v")).data.rows).toHaveLength(100);
});
it('does not mutate evidence, outputs, outbox, settings or runs while browsing',async()=>{await as(2);const snapshot=()=>call("select jsonb_build_object('evidence',(select count(*) from creative_kpi_brief_evidence),'outputs',(select count(*) from activity_automation_private.output_bindings),'outbox',(select count(*) from activity_automation_private.notification_outbox),'runs',(select count(*) from activity_automation_private.runs),'settings',(select to_jsonb(s) from activity_automation_private.settings s)) v");const before=await snapshot();await call("select activity_automation_monitor_summary('test','2026-09') v");await call("select activity_automation_monitor_notifications('production','2026-09') v");await call("select activity_automation_monitor_runs('test','2026-09') v");expect(await snapshot()).toEqual(before);});
it('projects explicit readiness booleans and safe blocking codes without raw evidence',async()=>{await as(2);await db.exec(`insert into battle_pass_private.production_ticks values('60000000-0000-4000-8000-000000000009','2026-09-18T01:00Z','readiness_checked',null,'{"sourceStatus":{"confirmed":false,"workingSheetLinked":true,"email":"DO_NOT_EXPOSE"},"sourceReady":false,"google":{"capabilitiesVerified":true,"token":"DO_NOT_EXPOSE"},"database":{"ready":"not a boolean","code":"schema_missing"},"plan":{"state":"blocked","issues":["source_invalid","secret token here"],"next":{"state":"waiting_confirmation","issues":["working_sheet_link"]}}}')`);
 const v=await call("select activity_automation_monitor_summary('production','2026-09','battle_pass') v");const ready=v.data.activities[0].lastSourceCheck;
 expect(ready).toMatchObject({sourceReady:false,confirmed:false,workingSheetLinked:true,googleReady:true,databaseReady:null,databaseCode:'schema_missing',issues:['source_invalid','working_sheet_link']});expect(new Date(ready.sourceCheckedAt).toISOString()).toBe('2026-09-18T01:00:00.000Z');expect(JSON.stringify(v)).not.toContain('DO_NOT_EXPOSE');
});
it('uses campaign month for overview notification attention but event month for notification history',async()=>{await as(1);await db.exec("update activity_automation_private.notification_outbox set created_at='2026-10-01T00:00Z'");try{
 const detail=await call("select activity_automation_monitor_run('shared','30000000-0000-4000-8000-000000000001') v");expect(detail.data.timeline.find((x:any)=>x.step==='notification').status).toBe('uncertain');
 expect((await call("select activity_automation_monitor_notifications('test','2026-10') v")).data.rows).toHaveLength(1);
 const sep=await call("select activity_automation_monitor_summary('test','2026-09','conqueror_crate') v");expect(sep.data.activities[0].notificationAttention).toBe(1);expect(sep.data.attention[0].entityType).toBe('notification');
 const oct=await call("select activity_automation_monitor_summary('test','2026-10','conqueror_crate') v");expect(oct.data.activities[0].notificationAttention).toBe(0);
 }finally{await db.exec("update activity_automation_private.notification_outbox set created_at='2026-09-18T00:00Z'");}});
it('bounds latest projection and checks a 2,000-record local stress dataset and query plan',async()=>{await as(1);await db.exec("insert into activity_automation_private.runs(id,activity,mode,is_test,project_code,state,stage,attempt_count,created_at,updated_at,model) select ('90000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'membership','test',true,'STRESS-'||n,'discovered','source',0,'2026-09-18T00:00Z','2026-09-18T00:00Z','{}' from generate_series(1,2000) n; analyze activity_automation_private.runs");
 const plan=await db.query("explain (format json) select id from activity_automation_private.runs where mode='test' and activity='membership' order by updated_at desc,id desc limit 1");
 const planText=JSON.stringify(plan.rows);expect(planText).toContain('Index Scan');expect(planText).toMatch(/activity_monitor_runs_(latest|event)_idx/);
 const start=performance.now();const v=await call("select activity_automation_monitor_summary('test','2026-09','membership') v");const page=await call("select activity_automation_monitor_runs('test','2026-09','membership') v");
 const elapsed=Math.round(performance.now()-start);console.info(`Monitor isolated stress: 2,000 added records; summary + page ${elapsed}ms; latest uses ${planText.match(/activity_monitor_runs_(latest|event)_idx/)?.[0]}`);
 expect(v.data.cards.complete).toBe(true);expect(page.data.rows).toHaveLength(25);expect(page.data.hasMore).toBe(true);expect(elapsed).toBeLessThan(15000);
},20000);
