import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {beforeAll,afterAll,beforeEach,it,expect} from 'vitest';
const sql=readFileSync('supabase/workgrid_control_center.sql','utf8');
const fixture=readFileSync('src/lib/control-center/fixture.sql','utf8');
const ids={admin:'00000000-0000-0000-0000-000000000001',requester:'00000000-0000-0000-0000-000000000002',
 assignee:'00000000-0000-0000-0000-000000000003',other:'00000000-0000-0000-0000-000000000004',work:'20000000-0000-0000-0000-000000000001'};
let db:PGlite;
async function actor(id:string|null=ids.admin,role='authenticated'){await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role',$2,false)",[id??'',role]);}
async function rpc(name:string,args:unknown[]=[]){return (await db.query<any>(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0]?.result;}
async function entity(kind:string,key:string){return (await db.query<any>('select * from wcc_private.entities where kind=$1 and key=$2',[kind,key])).rows[0];}
async function apply(kind:string,key:string,data:any,team:string|null=null){await actor();const old=await entity(kind,key);return rpc('wcc_apply',[kind,key,JSON.stringify(data),team,old?.version??0,'test configuration']);}
async function check(kind:string,key:string,evidence:any={}){const e=await entity(kind,key);await actor(null,'service_role');await rpc('wcc_record_check',[kind,key,e.version,true,JSON.stringify(evidence)]);await actor();}
async function setup(event='creative.review_requested'){
 const b=await entity('bot','creative');await check('bot','creative');await apply('bot','creative',{...b.data,state:'active'});
 const m=event==='creative.assigned'?ids.assignee:ids.requester;
 const profile={member_id:m.replace(/^00000000/,'10000000'),bot_key:'creative',channel:'direct',employment_type:'Fulltime',enabled:false,events:[event]};
 await apply('profile','test-profile',profile,'gdve');await check('profile','test-profile',{employee_code:'synthetic-employee'});
 await apply('profile','test-profile',{...profile,enabled:true},'gdve');
 const rule=await entity('rule','gdve:'+event);await apply('rule',rule.key,{...rule.data,enabled:true},'gdve');
 await rpc('wcc_set_runtime',[true,'local pilot']);
}
async function work(status='in_progress',type='creative_request'){
 await db.query('insert into public.work_items values($1,$2,$3,$4,$5,$6,$7,$8,null,null)',
 [ids.work,'CR-TEST','Synthetic work',type,status,'gdve',ids.requester,ids.assignee]);
}
async function deliveries(){return (await db.query<any>('select * from wcc_private.deliveries order by created_at')).rows;}
beforeAll(async()=>{db=new PGlite();await db.exec(fixture);await db.exec(sql);});
afterAll(async()=>db.close());
beforeEach(async()=>{await db.exec('reset role');await actor();await db.exec("delete from wcc_private.deliveries;delete from wcc_private.events;delete from public.work_items;delete from wcc_private.checks;delete from wcc_private.proposals;delete from wcc_private.audit;delete from wcc_private.reviewers;delete from wcc_private.entities where kind='profile' or key='test-group';update wcc_private.entities set data=jsonb_set(data,'{state}', '\"draft\"') where kind='bot';update wcc_private.entities set data=jsonb_set(data,'{enabled}','false') where kind='rule';update wcc_private.settings set runtime_enabled=false;");});
it('installer is idempotent and leaves sending disabled',async()=>{await db.exec(sql);await actor();expect((await rpc('wcc_workspace')).runtime).toBe(false);});
it('denies ordinary members and anonymous readers',async()=>{await actor(ids.requester);await expect(rpc('wcc_workspace')).rejects.toThrow('denied');await actor(null,'anon');await expect(rpc('wcc_workspace')).rejects.toThrow('denied');});
it('denies member apply and browser access to provider verification',async()=>{await actor(ids.requester);await expect(rpc('wcc_apply',['bot','creative','{}',null,1,'test'])).rejects.toThrow('Admin');await db.exec('set role authenticated');await expect(rpc('wcc_record_check',['bot','creative',1,true,'{}'])).rejects.toThrow('permission denied');await db.exec('reset role');});
it('private tables remain inaccessible to authenticated',async()=>{await db.exec('set role authenticated');await expect(db.query('select * from wcc_private.entities')).rejects.toThrow('permission denied');});
it('requires server-written verification before activation',async()=>{const b=await entity('bot','creative');await expect(apply('bot','creative',{...b.data,state:'active'})).rejects.toThrow('Check Bot');});
it('rejects forged verification fields and wrong credential reference',async()=>{const b=await entity('bot','creative');await expect(apply('bot','creative',{...b.data,verified:true})).rejects.toThrow('Unsupported field');await expect(apply('bot','creative',{...b.data,credential_ref:'SERVICE_ROLE_KEY'})).rejects.toThrow('Invalid Bot');});
it('rejects placeholder and wrong-bot group destinations',async()=>{await expect(apply('destination','test-group',{label:'Test',bot_key:'creative',group_id:'aaaaaabbbbbb',state:'draft'},'gdve')).rejects.toThrow('real group');});
it('detects optimistic version conflicts and records audit',async()=>{const b=await entity('bot','creative');await apply('bot','creative',{...b.data,label:'Edited'});await expect(rpc('wcc_apply',['bot','creative',JSON.stringify(b.data),null,b.version,'stale'])).rejects.toThrow('changed');expect((await db.query<any>("select count(*)::int n from wcc_private.audit")).rows[0].n).toBe(1);});
it('team reviewers can propose but cannot apply or read other teams',async()=>{await rpc('wcc_set_reviewer',[ids.requester,'gdve',true]);await actor(ids.requester);const ws=await rpc('wcc_workspace');expect(ws.admin).toBe(false);expect(ws.members.every((m:any)=>!m.teams.includes('mkt'))).toBe(true);const r=await entity('rule','gdve:creative.review_requested');const pid=await rpc('wcc_propose',['rule',r.key,JSON.stringify(r.data),'gdve',r.version,'proposal']);expect(pid).toBeTruthy();await expect(rpc('wcc_propose',['rule','mkt:creative.review_requested',JSON.stringify(r.data),'mkt',1,'wrong team'])).rejects.toThrow('reviewer');await expect(rpc('wcc_set_runtime',[true,'test'])).rejects.toThrow('Admin');});
it('proposal conflicts fail without applying or deciding',async()=>{const r=await entity('rule','gdve:creative.review_requested');const pid=await rpc('wcc_propose',['rule',r.key,JSON.stringify(r.data),'gdve',r.version,'proposal']);await apply('rule',r.key,{...r.data,label:'Changed'},'gdve');await expect(rpc('wcc_decide',[pid,true,'approve'])).rejects.toThrow('changed');expect((await db.query<any>('select status from wcc_private.proposals where id=$1',[pid])).rows[0].status).toBe('pending');});
it('Review dynamically selects requester, not assignee',async()=>{await setup();await work();await db.exec("update public.work_items set status='review'");const d=await deliveries();expect(d).toHaveLength(1);expect(d[0].recipient_id).toBe(ids.requester);expect(d[0].status).toBe('pending');});
it('ordinary saves during Review do not create another event',async()=>{await setup();await work('review');await db.exec("update public.work_items set status='review',title='Edited'");expect(await deliveries()).toHaveLength(1);});
it('re-review creates a new instance and cancels the old pending message',async()=>{await setup();await work('review');await db.exec("update public.work_items set status='in_progress';update public.work_items set status='review'");expect((await deliveries()).map(d=>d.status)).toEqual(['cancelled','pending']);});
it('requester replacement never silently reroutes old Review',async()=>{await setup();await work('review');await db.query('update public.work_items set requester_user_id=$1',[ids.other]);expect((await deliveries())[0].status).toBe('cancelled');});
it('unassigned creation does not notify everyone; assigned creation sends once',async()=>{await setup('creative.assigned');await work('unassigned');expect(await deliveries()).toHaveLength(0);await db.exec("update public.work_items set status='assigned';update public.work_items set status='assigned'");expect(await deliveries()).toHaveLength(1);});
it('inactive subscriptions and missing recipient route are explicit suppressions',async()=>{await setup();await work('review');const p=await entity('profile','test-profile');await apply('profile',p.key,{...p.data,enabled:false},'gdve');await db.exec("update public.work_items set status='in_progress';update public.work_items set status='review'");expect((await deliveries())[1].status).toBe('suppressed');});
it('runtime pause cancels pending and does not replay old events after enable',async()=>{await setup();await work('review');await rpc('wcc_set_runtime',[false,'pause']);await rpc('wcc_set_runtime',[true,'resume']);await actor(null,'service_role');expect(await rpc('wcc_claim')).toBeNull();expect((await deliveries())[0].status).toBe('cancelled');});
it('queued config revision changes cancel rather than silently reroute',async()=>{await setup();await work('review');const p=await entity('profile','test-profile');await apply('profile',p.key,{...p.data,seatalk_id:'123456789',enabled:false},'gdve');expect((await deliveries())[0].reason).toBe('configuration_changed');});
it('rechecks offboarded member access before claim',async()=>{await setup();await work('review');await db.query('update public.users set is_active=false where id=$1',[ids.requester]);await actor(null,'service_role');expect(await rpc('wcc_claim')).toBeNull();expect((await deliveries())[0].status).toBe('cancelled');await db.query('update public.users set is_active=true where id=$1',[ids.requester]);});
it('lease expiry after send started becomes uncertain, not automatic resend',async()=>{await setup();await work('review');await actor(null,'service_role');const c=await rpc('wcc_claim');expect(await rpc('wcc_mark_started',[c.delivery.id,c.delivery.lease_id])).toBe(true);await db.exec("update wcc_private.deliveries set lease_until=now()-interval '1 minute'");expect(await rpc('wcc_claim')).toBeNull();expect((await deliveries())[0].status).toBe('uncertain');});
it('stale lease cannot acknowledge a delivery',async()=>{await setup();await work('review');await actor(null,'service_role');const c=await rpc('wcc_claim');expect(await rpc('wcc_finish',[c.delivery.id,'ffffffff-ffff-ffff-ffff-ffffffffffff','provider_accepted','id',null])).toBe(false);});
it('uncertain retry requires explicit confirmation and never creates another task',async()=>{await setup();await work('review');await actor(null,'service_role');const c=await rpc('wcc_claim');await rpc('wcc_mark_started',[c.delivery.id,c.delivery.lease_id]);await rpc('wcc_finish',[c.delivery.id,c.delivery.lease_id,'uncertain',null,'timeout']);await actor();await expect(rpc('wcc_retry',[c.delivery.id,false,'retry'])).rejects.toThrow('confirmation');await rpc('wcc_retry',[c.delivery.id,true,'reviewed resend']);expect((await db.query<any>('select count(*)::int n from public.work_items')).rows[0].n).toBe(1);});
it('rollback of work transaction rolls back notification event',async()=>{await setup();await db.exec('begin');await work('review');await db.exec('rollback');expect(await deliveries()).toHaveLength(0);});
it('Task Assign uses FlowMate and waits for actual assignment',async()=>{const b=await entity('bot','flowmate');await check('bot','flowmate');await apply('bot','flowmate',{...b.data,state:'active'});const p={member_id:ids.assignee.replace(/^00000000/,'10000000'),bot_key:'flowmate',channel:'direct',employment_type:'Fulltime',enabled:false,events:['quick_task.assigned']};await apply('profile','test-profile',p,'gdve');await check('profile','test-profile',{employee_code:'synthetic'});await apply('profile','test-profile',{...p,enabled:true},'gdve');const r=await entity('rule','gdve:quick_task.assigned');await apply('rule',r.key,{...r.data,enabled:true},'gdve');await rpc('wcc_set_runtime',[true,'test']);await work('pending','quick_task');expect(await deliveries()).toHaveLength(0);await db.exec("update public.work_items set status='assigned'");expect((await deliveries())[0].bot_key).toBe('flowmate');expect((await deliveries())[0].recipient_id).toBe(ids.assignee);});
it('changing Bot app invalidates dependent profile verification',async()=>{await setup();const b=await entity('bot','creative');await apply('bot','creative',{...b.data,state:'draft',app_id:'different-app-id'});await work('review');expect((await deliveries())[0].status).toBe('suppressed');await actor(null,'service_role');expect(await rpc('wcc_claim')).toBeNull();});
it('TEST requests are idempotent and rate capped per Admin',async()=>{await setup();await db.exec('delete from wcc_private.test_requests');await actor(null,'service_role');const tid='50000000-0000-0000-0000-000000000001';expect(await rpc('wcc_test_claim',[tid,'profile','test-profile',ids.admin])).toBe(true);expect(await rpc('wcc_test_claim',[tid,'profile','test-profile',ids.admin])).toBe(false);await rpc('wcc_test_claim',['50000000-0000-0000-0000-000000000002','profile','test-profile',ids.admin]);await rpc('wcc_test_claim',['50000000-0000-0000-0000-000000000003','profile','test-profile',ids.admin]);await expect(rpc('wcc_test_claim',['50000000-0000-0000-0000-000000000004','profile','test-profile',ids.admin])).rejects.toThrow('rate limit');await db.exec('delete from wcc_private.test_requests');});
it('hidden membership confirmation requires exact verified destination TEST and Admin',async()=>{await setup();const dest={label:'Synthetic group',bot_key:'creative',group_id:'synthetic-group-id',state:'draft'};await apply('destination','test-group',dest,'gdve');await check('destination','test-group');const p=await entity('profile','test-profile');await apply('profile','test-profile',{...p.data,channel:'group',employment_type:'Freelance',seatalk_id:'123',destination_key:'test-group',enabled:false},'gdve');await actor(null,'service_role');const profile=await entity('profile','test-profile');await rpc('wcc_record_check',['profile','test-profile',profile.version,false,JSON.stringify({code:'member_list_hidden'})]);await actor();await expect(rpc('wcc_confirm_group_member',['test-profile','50000000-0000-0000-0000-000000000009','confirmed by recipient'])).rejects.toThrow('TEST');await actor(null,'service_role');const tid='50000000-0000-0000-0000-000000000009';await rpc('wcc_test_claim',[tid,'destination','test-group',ids.admin]);await rpc('wcc_test_finish',[tid,JSON.stringify({status:'provider_accepted'})]);await actor(ids.requester);await expect(rpc('wcc_confirm_group_member',['test-profile',tid,'confirmed'])).rejects.toThrow('Admin');await actor();await rpc('wcc_confirm_group_member',['test-profile',tid,'recipient confirmed presence and seeing TEST']);const checked=await db.query<any>("select verified,evidence from wcc_private.checks where kind='profile' and key='test-profile'");expect(checked.rows[0].verified).toBe(true);expect(checked.rows[0].evidence.method).toBe('human_confirmation_not_api_membership');await db.exec('delete from wcc_private.test_requests');});
it('accepted substeps are recorded only for the current started lease',async()=>{await setup();await work('review');await actor(null,'service_role');const c=await rpc('wcc_claim');expect(await rpc('wcc_record_step',[c.delivery.id,c.delivery.lease_id,'message','test-id'])).toBe(false);await rpc('wcc_mark_started',[c.delivery.id,c.delivery.lease_id]);expect(await rpc('wcc_record_step',[c.delivery.id,c.delivery.lease_id,'message','test-id'])).toBe(true);expect((await deliveries())[0].steps.message.accepted).toBe(true);});
it('navigation access is explicit for Admin and designated reviewers only',async()=>{expect(await rpc('wcc_access')).toBe(true);await actor(ids.requester);expect(await rpc('wcc_access')).toBe(false);await actor();await rpc('wcc_set_reviewer',[ids.requester,'gdve',true]);await actor(ids.requester);expect(await rpc('wcc_access')).toBe(true);});
it('impact counts are live and denied across reviewer team boundaries',async()=>{await setup();await work('review');expect((await rpc('wcc_impact',['profile','test-profile'])).pending).toBe(1);await rpc('wcc_set_reviewer',[ids.other,'mkt',true]);await actor(ids.other);await expect(rpc('wcc_impact',['profile','test-profile'])).rejects.toThrow('Scope');await expect(rpc('wcc_impact',['runtime','all'])).rejects.toThrow('Admin');});
